// Display mirror of server/src/gameModes.js. The server also sends the live
// list on every lobby update; this is the fallback so the hub renders
// instantly before the first socket message lands.
export const MODE_LIST = [
  {
    id: 'classic',
    name: 'Classic 1v1',
    tagline: 'Best of 3, win by 2',
    icon: '⚔️',
    blurb: 'Head-to-head against a real player when one is around. First to lead by two takes it.',
    solo: false,
    pvp: true,
    wager: false,
  },
  {
    id: 'duo',
    name: 'Duos 2v2',
    tagline: 'Two of you, one call each',
    icon: '🤝',
    blurb: 'Two a side. Agree and you score double — disagree and you cancel each other out.',
    solo: false,
    pvp: true,
    teamSize: 2,
    wager: false,
  },
  {
    id: 'survival',
    name: 'Survival',
    tagline: 'One wrong call and it’s over',
    icon: '💀',
    blurb: 'No safety net. Every correct call pays more than the last — last one standing wins.',
    solo: true,
    pvp: true,
    wager: false,
  },
  {
    id: 'blitz',
    name: 'Blitz',
    tagline: '60 seconds. Call as many as you can',
    icon: '⚡',
    blurb: 'Four seconds a round against the clock. Highest net score takes it.',
    solo: true,
    pvp: true,
    wager: false,
  },
  {
    id: 'stakes',
    name: 'High Stakes',
    tagline: 'Wager coins. Double or nothing',
    icon: '🎰',
    blurb: 'Put coins on the line. Win doubles it — against a real player it is their stake you win.',
    solo: false,
    pvp: true,
    wager: true,
    wagerOptions: [100, 250, 500, 1000],
  },
  {
    id: 'gauntlet',
    name: 'Gauntlet',
    tagline: 'Beat 3 rivals, each tougher',
    icon: '🏆',
    blurb: 'Three stages, three rounds each. Fall behind in any of them and the run is over.',
    solo: false,
    pvp: true,
    wager: false,
  },
  {
    id: 'tournament',
    name: 'Tournament',
    tagline: '8 players, one winner takes the pot',
    icon: '🥇',
    blurb: 'Entry costs a tenth of your coins. Eight players enter, every entry goes into one pot, and three wins takes it.',
    solo: false,
    pvp: true,
    bracket: true,
    wager: false,
  },
  {
    id: 'custom',
    name: 'Custom Room',
    tagline: 'Play a friend with a code',
    icon: '🎟️',
    blurb: 'Make a room, send the code, and play whichever mode you like against a friend.',
    solo: false,
    room: true,
    wager: false,
  },
];

export const MODE_BY_ID = Object.fromEntries(MODE_LIST.map((m) => [m.id, m]));
